version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2021.10
    steps:
      - checkout
      - run:
          name: Install mdbook
          command: |
            wget https://github.com/rust-lang/mdBook/releases/download/v0.4.13/mdbook-v0.4.13-x86_64-unknown-linux-gnu.tar.gz
            tar zxvf mdbook-v0.4.13-x86_64-unknown-linux-gnu.tar.gz
            chmod +x mdbook
      - run: ./mdbook build
      # - run: ./mdbook test
      - persist_to_workspace:
          root: "."
          paths: [ "book" ]

  deploy-website:
    docker:
      - image: cimg/base:2021.10
    steps:
      - checkout
      - attach_workspace: { at: "." }
      - add_ssh_keys:
          fingerprints:
            # repo-specific deploy key
            - "01:35:41:49:e3:f1:cd:43:1c:a8:5b:80:e4:62:b8:63"
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "ops@darklang.com"
            git config --global user.name "Dark Ops"
            git worktree add /tmp/book gh-pages
            rm -rf /tmp/book/* # this won't delete the .git directory
            cp -rp book/* /tmp/book/
            cd /tmp/book
            git add -A
            git commit "[skip ci] Automated Deploy of $CIRCLE_SHA1 via CircleCI"
            GIT_USER=none USE_SSH=true git push origin gh-pages

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy-website:
          requires: ["build"]
          filters:
            branches:
              only:
                - main
